name: talas
description: The app for connecting with similar people.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6+1
  flutter_secure_storage: ^7.0.1
  provider: ^6.0.5
  fixnum: ^1.0.1
  protobuf: ^2.1.0
  grpc: ^3.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_image_compress: ^1.1.3
  date_time_picker: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  mailto: ^2.0.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  assets_gen: ^1.4.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/main/account/decoration.svg
    - assets/default_pfp.png
    - assets/main/account/location.svg
    - assets/main/account/envelope.svg
    - assets/main/communities/placeholder_picture.png
    - assets/welcome/background.png
    - assets/welcome/invisible.svg
    - assets/welcome/visible.svg

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"