// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 11.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'talas';

  static const String assets_default_pfp_png = 'assets/default_pfp.png';
  static const String talas$assets_default_pfp_png = 'packages/talas/assets/default_pfp.png';

  static const String assets_main_account_decoration_svg = 'assets/main/account/decoration.svg';
  static const String talas$assets_main_account_decoration_svg = 'packages/talas/assets/main/account/decoration.svg';

  static const String assets_main_account_delete_svg = 'assets/main/account/delete.svg';
  static const String talas$assets_main_account_delete_svg = 'packages/talas/assets/main/account/delete.svg';

  static const String assets_main_account_edit_svg = 'assets/main/account/edit.svg';
  static const String talas$assets_main_account_edit_svg = 'packages/talas/assets/main/account/edit.svg';

  static const String assets_main_account_envelope_svg = 'assets/main/account/envelope.svg';
  static const String talas$assets_main_account_envelope_svg = 'packages/talas/assets/main/account/envelope.svg';

  static const String assets_main_account_location_svg = 'assets/main/account/location.svg';
  static const String talas$assets_main_account_location_svg = 'packages/talas/assets/main/account/location.svg';

  static const String assets_main_account_logout_svg = 'assets/main/account/logout.svg';
  static const String talas$assets_main_account_logout_svg = 'packages/talas/assets/main/account/logout.svg';

  static const String assets_main_communities_placeholder_picture_png = 'assets/main/communities/placeholder_picture.png';
  static const String talas$assets_main_communities_placeholder_picture_png = 'packages/talas/assets/main/communities/placeholder_picture.png';

  static const String assets_welcome_background_png = 'assets/welcome/background.png';
  static const String talas$assets_welcome_background_png = 'packages/talas/assets/welcome/background.png';

  static const String assets_welcome_invisible_svg = 'assets/welcome/invisible.svg';
  static const String talas$assets_welcome_invisible_svg = 'packages/talas/assets/welcome/invisible.svg';

  static const String assets_welcome_visible_svg = 'assets/welcome/visible.svg';
  static const String talas$assets_welcome_visible_svg = 'packages/talas/assets/welcome/visible.svg';
}
